### ISSUE TITLE
Sdk bug?

### ISSUE THREAD

**Issue by neuroupdate** [Microsoft/activities#2]
With Lumia 735 and "Activities - Lumia SensorCore 1.1.0.17". Hold phone and put phone down after couple second then current activity is idle? Hold phone up and after couple seconds current activity is stationary? Similar results with own code .GetActivityHistoryAsync so must be SDK on phone related?

**Comment by ltomuta** [comment]
Sounds like correct behaviour to me. You moved the phone around but you yourself are not moving, ergo you are stationary.

--- Original Message ---

**Comment by neuroupdate** [comment]
You are correct https://msdn.microsoft.com/en-us/library/dn932084.aspx. I thought wrongly idle label should be more activity than stationary
